/*
File: table_previews.sql
Purpose: Preview records from all raw tables.
Author: Tony Blair
Date: 2026-06-09
*/
USE DATABASE  HBP_PRACTICE;
USE SCHEMA    RAW;
USE WAREHOUSE PRACTICE_WH;

SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();
-- Preview customers data
SELECT *
FROM HBP_PRACTICE.RAW.CUSTOMERS
LIMIT 10;

-- Preview products data
SELECT *
FROM HBP_PRACTICE.RAW.PRODUCTS
LIMIT 10;

-- Preview orders data
SELECT *
FROM HBP_PRACTICE.RAW.ORDERS
LIMIT 10;
SELECT * FROM CUSTOMERS LIMIT 10;

SELECT * FROM PRODUCTS LIMIT 10;

SELECT * FROM ORDERS LIMIT 10;